#!/bin/bash

case $1 in
patch)
    ;;
install_deps)
    sudo apt-get -y install python-pip
    pip install  --user sphinx
    pip install --user sphinx_rtd_theme
    ;;
configure)
    ;;
compile)
    export PATH=~/.local/bin:$PATH
    make html
    ;;
check)
    ;;
package)
    ;;
upload)
      #setup ssh agent for key forwarding to work
      #eval ssh-agent $SHELL
      eval "$(ssh-agent)"
      ssh-add ~/.ssh/id_rsa

      rsync -avz _build/html tchpc@$DOCS_HOST:docs/
    ;;
compile_extra)
    ;;
uninstall_deps)
    ;;
esac
